### DISCUSSION TITLE
Using the Blueprint scripts in Homeassistant UI

### DISCUSSION THREAD

**Discussion by nakermann1973** [mundschenk-at/ha-valetudo-blueprints#5] [General]
https://valetudo.cloud/pages/integrations/home-assistant-integration.html shows how to create a lovelace entity where the rooms can be selected and then a script called to clean just those rooms.

This is done by using a group containing all the segments as input_boolean toggles, and populating the MQTT message with all segments where the toggle is true.

Do you have any suggestions on how to achieve the same using your blueprint script (i.e. using a list of segments, selectable in the UI, to pass to the script)?

**Comment by mundschenk-at** [comment]
Basically, you don't need the customized attributes (`room_id`) because you can directly pass the concatenated names of input elements to the script. (Since I dislike adding so many input elements, I've just used Mushroom Cards chips to trigger single-room cleaning and a schedule for the whole flat.)

**Reply by nakermann1973** [reply]
Makes sense.  I also dislike the way mentioned in the valetudo docs of repeating all the segments and entities in the yaml config.

What I was experimenting with at the moment was to create a template sensor which just contains the names of the selected segment group members.  This does work, but I probably don't need it if I just do single-room cleaning.

The template sensor uses the following to create a comma-separated list, in case it is interesting to anyone:

```
{{expand("group.vacuum_rooms") | selectattr("state","eq","on") | map(attribute="attributes.friendly_name") | list | join(",")  }}
```

**Reply by mundschenk-at** [reply]
You would not need a template sensor but just use pass this template to the script input variable:

```yaml
  - service: script.your_robot_clean_rooms
    data:
      segments: {{expand("group.vacuum_rooms") | selectattr("state","eq","on") | map(attribute="attributes.friendly_name") | list | join(",")  }}
      iterations: 2
```
