### ISSUE TITLE
valetudo_notifications

### ISSUE THREAD

**Issue by Antexa** [mundschenk-at/ha-valetudo-blueprints#2]
I got several error on notification script

Any hints ? 

Automation configuration : 
```
alias: "Valetudo: Notifications"
description: ""
use_blueprint:
  path: mundschenk-at/valetudo-notifications.yaml
  input:
    vacuum: vacuum.valetudo_robot
    rendered_map: camera.valetudo_robot_map_data
    error_message: sensor.valetudo_robot_error_description
    notify_device:
      - 1d89
      - fbf6
```

Logs output :
> Logger: homeassistant.components.automation.valetudo_notifications
> Source: components/automation/__init__.py:253 
> Integration: Automation (documentation, issues) 
> First occurred: 09:20:58 (1 occurrences) 
> Last logged: 09:20:58
> 
> Error while executing automation automation.valetudo_notifications: Template rendered invalid service: notify.
> 

> Logger: homeassistant.components.automation.valetudo_notifications
> Source: helpers/script.py:1067 
> Integration: Automation (documentation, issues) 
> First occurred: November 2, 2022 at 09:10:09 (22 occurrences) 
> Last logged: 09:20:58
> 
> Valetudo: Notifications: Error executing script. Error for repeat at pos 1: Template rendered invalid service: notify.
